{
 "title": "RoomIT | SUI",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inteval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "GENERAL INFORMATIONS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BATCH SIZE COUNT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "batch_size_count{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "BATCH SIZE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "batch_size_sum{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "TOTAL TRANSACTION CERTIFICATE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "total_transaction_certificates{instance=\"testnet-02.roomit.xyz:9184\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GOSSIP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GOSSIP QUEUE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gossip_queued_count{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GOSSIP ERROR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gossip_task_error_count{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GOSSIP SUCCESS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gossip_task_success_count{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GOSSIP SYNC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gossip_sync_count{}", "legendFormat": "__auto" }
   ]
  },
  { "title": "OBJECT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "INPUT SUMMARY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 11 },
   "targets": [
    { "expr": "num_input_objects_sum{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "INPUT COUNT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_input_objects_count{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SHARED SUMMARY",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 11 },
   "targets": [
    { "expr": "num_shared_objects_sum{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SHARED COUNT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_shared_objects_count{}", "legendFormat": "__auto" }
   ]
  }
 ]
}