# my global config
global:
  scrape_interval: 1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  scrape_timeout: 1m
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
## PRODUCTION APPLICATIONS METRICS
  - job_name: "Production"
    metrics_path: '/metrics'
    static_configs:
      - targets: ["mainnet-01.roomit.xyz:9100","system.roomit.xyz:9100"]
  - job_name: "azero-testnet"
    metrics_path: '/metrics'
    static_configs:
            - targets: ["testnet-02.roomit.xyz:9615"]

## TESTNET APPLICATIONS METRICS
  - job_name: "Staging"
    metrics_path: '/metrics'
    static_configs:
            - targets: ["testnet-02.roomit.xyz:9100","testnet-01.roomit.xyz:9100"]

  - job_name: "sui-testnet"
    metrics_path: '/metrics'
    static_configs:
            - targets: ["testnet-01.roomit.xyz:9184"]

  - job_name: "celestia-testnet"
    metrics_path: '/metrics'
    static_configs:
            - targets: ["testnet-02.roomit.xyz:26660"]
