{
 "title": "RoomIT | Aptos Validator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "NODE RESOURCES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Server / Days",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=\"testnet-02\"} / 86400"
    }
   ]
  },
  {
   "title": "CPU Idles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_idle{host=\"testnet-02\",cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "CPU Usages Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_user{host=\"testnet-02\",cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "CPU Usages System",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_system{host=\"testnet-02\",cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "Memory Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_available_percent{host=\"testnet-02\"}"
    }
   ]
  },
  {
   "title": "Container Memory Used",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_mem_usage_percent{container_name=\"aptos-roomit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_cpu_usage_percent{container_name=\"aptos-roomit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk  Usage",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(device, path) (disk_used_percent{device=\"sdb\"}) or sum by(device, path) (disk_used_percent{device=\"sda1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Idles",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "sum by(host) (cpu_usage_idle{host=\"testnet-02\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "CPU Usages System",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(host) (cpu_usage_system{host=\"testnet-02\", cpu=\"cpu-total\"})"
    }
   ]
  },
  {
   "title": "Container CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_cpu_usage_percent{container_name=\"aptos-roomit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(container_name) (docker_container_mem_usage_percent{container_name=\"aptos-roomit\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GENERAL INFORMATIONS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Advertise Sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_state_sync_version{type=\"synced\"}"
    }
   ]
  },
  {
   "title": "Own Sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_data_client_highest_advertised_data"
    }
   ]
  },
  {
   "title": "Delay Sync",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_num_blocks_in_tree "
    }
   ]
  },
  {
   "title": "All Sync Block",
   "type": "stat",
   "description": "Left :\nOutbound\nTransaction Commit\nSynced\nEpoch",
   "gridPos": { "h": 4, "w": 7, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aptos_state_sync_version", "legendFormat": " " }
   ]
  },
  {
   "title": "Proposal",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_proposals_count"
    }
   ]
  },
  {
   "title": "Vote Ratio",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(aptos_consensus_vote_nil_count / aptos_consensus_current_round) * 100"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aptos_storage_next_block_epoch", "legendFormat": " " }
   ]
  },
  {
   "title": "Vote Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aptos_consensus_vote_nil_count", "legendFormat": " " }
   ]
  },
  {
   "title": "Uptime Service",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (count(rate(aptos_consensus_current_round[10m]) > 0) OR on() vector(0)) / quantile(0.67, aptos_consensus_current_epoch_validators)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Inbound",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_connections{role_type=\"validator\",direction=\"inbound\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transfer",
   "type": "gauge",
   "description": "Transfer Per Second",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_consensus_last_committed_version / 10000"
    }
   ]
  },
  {
   "title": "Outbound",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aptos_connections{direction=\"outbound\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Round",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aptos_consensus_current_round", "legendFormat": " " }
   ]
  },
  {
   "title": "Proposal/Hours",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aptos_consensus_proposals_count[1h])"
    }
   ]
  },
  {
   "title": "Vote/Hours",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aptos_consensus_vote_nil_count[1h])"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Chain ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(api_node_role) (aptos_api_chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request HTTP Code Count ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(operation_id) (rate(aptos_api_requests_count[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response HTTP Code Count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (aptos_api_response_status_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "VALIDATOR CONNECTIVITY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Total Connected Peers",
   "type": "timeseries",
   "description": "Total Connected Peers for both inbound and outbound per peer.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(role_type, network_id) (aptos_connections{network_id=\"Validator\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inbound Connected Peers",
   "type": "timeseries",
   "description": "Total Inbound connected peers. There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (role_type, network_id) (aptos_connections{network_id=\"Validator\", role_type=\"validator\", direction=\"inbound\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Outbound Connected Peers",
   "type": "timeseries",
   "description": "Total Inbound connected peers. There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (role_type, network_id) (aptos_connections{network_id=\"Validator\", role_type=\"validator\", direction=\"outbound\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Telemetry/5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(aptos_telemetry_success[5m])",
     "legendFormat": " "
    }
   ]
  },
  { "title": "SYNC AND VOTING", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Inbound Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_network_inbound_rpc_handler_latency_seconds_bucket[10m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Outbound Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_network_outbound_rpc_request_latency_seconds_bucket[10m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Vote/3m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_vote_nil_count[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Syncing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(aptos_state_sync_version[1h])",
     "legendFormat": " "
    }
   ]
  },
  { "title": "BLOCK INFORMATIONS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Block Creation Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_tracing_sum[10m]) / rate(aptos_consensus_block_tracing_count[10m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Block Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_execute_block_seconds_bucket[10m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(aptos_executor_execute_block_seconds_bucket[10m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_execute_block_seconds_bucket[10m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Pending Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_consensus_num_blocks_in_tree - 1",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Block Tracing Bucket",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aptos_consensus_block_tracing_bucket",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "CONSENSUS AND PROPOSAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Consensus Timeout Count/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_timeout_count[5m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Consensus Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(consensus_duration_sum[10m])",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Consensus 1 Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_vote_nil_count[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proposal/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aptos_consensus_proposals_count[3m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}