{
 "title": "RoomIT | AlephZero",
 "description": "Grafana dashboard for substrate",
 "tags": [
  "substrate",
  "blockchain",
  "node",
  "polkadot",
  "kusama",
  "azero"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(status) (substrate_block_height)"
    }
   ]
  },
  {
   "title": "P2P Connection Closed",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(reason, direction) (substrate_sub_libp2p_connections_closed_total)"
    }
   ]
  },
  {
   "title": "State Cashe (bytes)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 7, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "substrate_state_cache_bytes", "legendFormat": "Size (bytes)" }
   ]
  },
  {
   "title": "Total Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "substrate_sync_peers" }
   ]
  },
  {
   "title": "P2P Pending Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_pending_connections"
    }
   ]
  },
  {
   "title": "P2P Listener Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_listeners_errors_total"
    }
   ]
  },
  {
   "title": "Incoming Traffic Block P2P",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_incoming_connections_total"
    }
   ]
  },
  {
   "title": "P2P Request Success Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_requests_in_success_total_sum"
    }
   ]
  },
  {
   "title": "P2P Connection Open",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_connections_opened_total"
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Imported -> Ordering",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Ordering" }
   ]
  },
  {
   "title": "Imported -> Ordering (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Ordering)" },
    { "expr": "stddev(aleph_Ordering)" }
   ]
  },
  {
   "title": "Importing -> Finalized",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "aleph_Imported + aleph_Ordering + aleph_Ordered + aleph_Aggregating + aleph_Finalized"
    }
   ]
  },
  {
   "title": "Ordering -> Ordered",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Ordered" }
   ]
  },
  {
   "title": "Ordered -> Aggregating",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "aleph_Aggregating" }
   ]
  },
  {
   "title": "Ordering -> Ordered (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Ordered)" },
    { "expr": "stddev(aleph_Ordered)" }
   ]
  },
  {
   "title": "Ordered -> Aggregating (avg, stddev)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "avg(aleph_Aggregating)" },
    { "expr": "stddev(aleph_Aggregating)" }
   ]
  },
  {
   "title": "Other metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "txps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions / (aleph_Imported + aleph_Ordering + aleph_Ordered + aleph_Aggregating + aleph_Finalized)"
    }
   ]
  },
  {
   "title": "Block Height (best)",
   "type": "stat",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\"}",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\"}",
     "legendFormat": "Height(finalized)"
    }
   ]
  },
  {
   "title": "LibP2P peers",
   "type": "graph",
   "description": "Number of connected peers",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "Peers" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count",
     "legendFormat": "Number of network gossip peers"
    }
   ]
  },
  {
   "title": "Max block construction time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_proposer_block_constructed_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max block verification time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_block_verification_time_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max block proposal  time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_proposer_block_proposal_time_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Max block verification and import time",
   "type": "timeseries",
   "description": "https://www.notion.so/cardinalcryptography/2022-03-Histogram-block-metrics-in-Substrate-4b9f2cdc083f4a4585c73429ceef077c",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(\n    histogram_quantile(1, rate(substrate_block_verification_and_import_time_bucket{app=\"aleph-node-validator\"}[5m])),\n    \"region_ip\",\n    \"$1$2\",\n    \"instance\",\n    \"([0-9]*)\\\\.([0-9]*)\\\\..*\"\n) + on (region_ip) group_left(topology_kubernetes_io_region) 0 * count by (region_ip, topology_kubernetes_io_region)\n(\n    label_replace(\n      container_memory_max_usage_bytes{},\n      \"region_ip\",\n      \"$1$2\",\n      \"instance\",\n      \"ip-([0-9]*)-([0-9]*)-.*\"\n    )\n)",
     "legendFormat": "{{topology_kubernetes_io_region}} {{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}